"""
helpers.const.config
~~~~~~~~~~~~~~~~~~~~

This module defines and centralizes heavily used constants which used to be
defined all throughout the app.

:copyright: (c) 2023 Aderis Energy

Notes
-----

 - The contents of this file were generated by:
     `PV_DASH_RemoteUI/scripts/const_generators/gen_const.py`
 
 - We use `+` for literal-string concatenation rather than a format string
   (`f""`, `%`, `''.format`) so that mouse hovering a variable in an IDE will
   show the literal-string path rather than `LiteralString` or `str`.

"""


from helpers.globalconstants import CONFIG_INTERNAL, SOS_CONFIG


############################### START CONSTANTS ################################


#                                                      config_internal Constants
# generated by the config_internal generator

#gen:start:config_internal
AVAILABLE_DASHBOARD_TILES = CONFIG_INTERNAL + '/available_dashboard_tiles.json'
BACKGROUND_VERSIONS = CONFIG_INTERNAL + '/background_versions.json'
DASHBOARD_TILE_INFO = CONFIG_INTERNAL + '/dashboard_tile_info.json'
#gen:end:config_internal


#                                                           sos-config Constants
# generated by the sos-config generator

#gen:start:sos-config
ALARMS = SOS_CONFIG + '/alarms.json'
ALARM_PROF = SOS_CONFIG + '/alarm_prof.json'
APP_BACKUPS = SOS_CONFIG + '/app-backups.json'
ASSET_MEASURES = SOS_CONFIG + '/asset_measures.json'
ASSET_PARAMETERS = SOS_CONFIG + '/asset_parameters.json'
ASSET_PARAMETERS_CAN_EDIT = SOS_CONFIG + '/asset_parameters_can_edit.json'
BACKGROUND = SOS_CONFIG + '/background.json'
BATTERY_CONTROL = SOS_CONFIG + '/battery_control.json'
CAMERAS = SOS_CONFIG + '/cameras.json'
DASHBOARDS = SOS_CONFIG + '/dashboards.json'
DASHBOARD_TILES = SOS_CONFIG + '/dashboard_tiles.json'
DEFAULT_GOLDEN = SOS_CONFIG + '/default_golden.json'
DEVICE_TEMPLATES = SOS_CONFIG + '/device_templates.json'
DEV_SINGLE_LINE = SOS_CONFIG + '/devSingLine.json'
DNP3_AGENT_CONFIG = SOS_CONFIG + '/dnp3_agent_config.json'
DOCUMENTS = SOS_CONFIG + '/documents.json'
INDEXES = SOS_CONFIG + '/indexes.json'
INITIALIZED = SOS_CONFIG + '/initialized.json'
KPIS_HISTORY_MODEL = SOS_CONFIG + '/kpis_history_model.json'
KPI_MODELS = SOS_CONFIG + '/kpi_models.json'
LAST_GOLDEN = SOS_CONFIG + '/last_golden.json'
MODBUS_CALL_GROUPS = SOS_CONFIG + '/modbus_call_groups.json'
MODEL_DATA = SOS_CONFIG + '/model_data.json'
NETWORK = SOS_CONFIG + '/network.json'
NOTIFICATION_LIMITER = SOS_CONFIG + '/notification_limiter.json'
OLD_REPORTS = SOS_CONFIG + '/old_reports.json'
OPCUA_CONFIG = SOS_CONFIG + '/opcua_config.json'
PLANT_CONFIG = SOS_CONFIG + '/plant_config.json'
PROCESSED_TIMES = SOS_CONFIG + '/processed_times.json'
REPORTS = SOS_CONFIG + '/reports.json'
ROLES = SOS_CONFIG + '/roles.json'
SITE_DEVICES = SOS_CONFIG + '/site_devices.json'
SOS_TEMPLATES = SOS_CONFIG + '/sos_templates.json'
SOS_TEMPLATES_DNP3 = SOS_CONFIG + '/sos_templates_dnp3.json'
SOS_TEMPLATES_MODBUS = SOS_CONFIG + '/sos_templates_modbus.json'
SOS_TEMPLATES_SNMP = SOS_CONFIG + '/sos_templates_snmp.json'
STORAGE_SCHEDULE_BLOCKS = SOS_CONFIG + '/storage_schedule_blocks.json'
SUNSPECTOR_TRACKER_MOTOR = SOS_CONFIG + '/sunspector_tracker_motor.json'
SYSTEM_INFO = SOS_CONFIG + '/system_info.json'
SYSTEM_INFO2 = SOS_CONFIG + '/system_info2.json'
TEMPLATE_ASSOCIATIONS = SOS_CONFIG + '/template_associations.json'
TILE_CONFIG = SOS_CONFIG + '/tile_config.json'
TIMEZONES = SOS_CONFIG + '/timezones.json'
TRACKER_CONTROL_CONFIG = SOS_CONFIG + '/tracker_control_config.json'
TRACKER_SIM = SOS_CONFIG + '/tracker_sim.json'
UNIT_CONVERSION = SOS_CONFIG + '/unit_conversion.json'
UNIT_REFERENCE = SOS_CONFIG + '/unit_reference.json'
UPDATES = SOS_CONFIG + '/updates.json'
USERS = SOS_CONFIG + '/users.json'
USER_DASHBOARDS = SOS_CONFIG + '/user_dashboards.json'
USER_LAYOUTS = SOS_CONFIG + '/user_layouts.json'
USER_TYPES = SOS_CONFIG + '/user_types.json'
VIRTUAL_DEVICES = SOS_CONFIG + '/virtual_devices.json'
VIRTUAL_MAPPINGS = SOS_CONFIG + '/virtual_mappings.json'
#gen:end:sos-config


################################ END CONSTANTS #################################

